_BASE_: maskformer2_R50_bs16_160k.yaml
OUTPUT_DIR: "./experiments"
MODEL:
  RASS:
    pretrained_sd_model_path: "/data/guankai/RASS/preset/model/stable-diffusion-2-1-base"
    pretrained_res_model_path: "/data/guankai/RASS/preset/model/scr.pkl"
    opt: "/data/guankai/RASS/preset/train_realesrnet_x1_get_degration.yml"
    ram_ft_path: "/data/guankai/RASS/preset/model/DAPE.pth"
    ram_path: "/data/guankai/RASS/preset/model/ram_swin_large_14m.pth"
  META_ARCHITECTURE: "MaskFormer_rass"
  BACKBONE:
    NAME: "RASS"
  FEATURE_PROJECTION:
    FEATURE_DIMS: [256, 512, 1280, 1280, 640, 320]
    GROUPED_INDICES: [[0], [1], [2], [3], [4], [5]]
    FEATURE_STRIDES: [4, 8, 32, 16, 8, 8]
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
SOLVER:
  IMS_PER_BATCH: 8


